# iaas-frontend-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: iaas-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iaas-frontend
  template:
    metadata:
      labels:
        app: iaas-frontend
    spec:
      containers:
      - name: iaas-frontend-container
        image: caschuen/iaas-frontend  # Replace with the name of your Docker image
        ports:
        - containerPort: 80

---
# iaas-frontend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: iaas-frontend-service
spec:
  selector:
    app: iaas-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP 


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: iaas-frontend-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /iaas-frontend
        pathType: Exact
        backend:
          service:
            name: iaas-frontend-service
            port:
              number: 80