# mlops-iaas-deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-iaas-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-iaas
  template:
    metadata:
      labels:
        app: mlops-iaas
    spec:
      containers:
      - name: mlops-iaas-container
        image: caschuen/mlops-iaas  # Replace with the name of your Docker image
        ports:
        - containerPort: 8000

---
# mlops-iaas-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: mlops-iaas-service
spec:
  selector:
    app: mlops-iaas
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP 


---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mlops-iaas-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /predict_fuel_consumption_l_100_km
        pathType: Exact
        backend:
          service:
            name: mlops-iaas-service
            port:
              number: 80